[package]
name = "pyannote-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
hound = "3.5.1"
ndarray = "0.15.6"
ort = "2.0.0-rc.4"
knf-rs = "0.1.0"


[[example]]
name = "diarize"
